import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Sandun LB
 */
public class Assign extends javax.swing.JFrame {

    /**
     * Creates new form Assign
     */
    public Assign() {
        initComponents();
        showData();
        
    }
    public void showData(){
Connection con = Database.connection();
        
        try {
    Statement stmt = con.createStatement();
    ResultSet rs = stmt.executeQuery("SELECT * FROM employment_details");

    DefaultTableModel model = new DefaultTableModel(
        new Object[][]{
            {null, null, null, null, null, null}
        },
        new String[]{
            "Employee ID", "Department", "Job Title", "Employee Status", "Hire Date", "Salary"
        }
    );

    while (rs.next()) {
        int employeeId = rs.getInt("employee_id");
        String department = rs.getString("department");
        String jobTitle = rs.getString("job_title");
        String employmentStatus = rs.getString("employment_status");
        String hireDate = rs.getString("hire_date");
        BigDecimal salary = rs.getBigDecimal("salary");

        model.addRow(new Object[]{employeeId, department, jobTitle, employmentStatus, hireDate, salary});
    }

    view.setModel(model);
} catch (SQLException e) {
    e.printStackTrace();
    JOptionPane.showMessageDialog(null, "Error fetching data from the database.");
}
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtemploymentstatus = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txthiredate = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btn1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtsalary = new javax.swing.JTextField();
        txtemployeeid = new javax.swing.JTextField();
        btn2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtjobtitle = new javax.swing.JTextField();
        txtdepartment = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        view = new javax.swing.JTable();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtemploymentstatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemploymentstatusActionPerformed(evt);
            }
        });
        getContentPane().add(txtemploymentstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 213, 149, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 255));
        jLabel1.setText("Assign Employees");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 31, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 255));
        jLabel3.setText("Job Title:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 173, -1, -1));
        getContentPane().add(txthiredate, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 257, 149, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 255));
        jLabel5.setText("Employee Status:");
        jLabel5.setToolTipText("");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 213, -1, -1));

        btn1.setBackground(new java.awt.Color(0, 165, 89));
        btn1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn1.setForeground(new java.awt.Color(255, 255, 255));
        btn1.setText("Save");
        btn1.setToolTipText("");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 255));
        jLabel6.setText("Hire Date:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 257, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 255));
        jLabel7.setText("Salary:");
        jLabel7.setToolTipText("");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 297, -1, -1));

        txtsalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsalaryActionPerformed(evt);
            }
        });
        getContentPane().add(txtsalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 297, 149, -1));
        getContentPane().add(txtemployeeid, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 93, 149, -1));

        btn2.setBackground(new java.awt.Color(102, 102, 255));
        btn2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn2.setForeground(new java.awt.Color(255, 255, 255));
        btn2.setText("Back");
        btn2.setToolTipText("");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 255));
        jLabel2.setText("Employee ID:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 93, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 255));
        jLabel4.setText("Department:");
        jLabel4.setToolTipText("");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 133, -1, -1));
        getContentPane().add(txtjobtitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 173, 149, -1));
        getContentPane().add(txtdepartment, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 133, 149, -1));

        view.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        view.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Employee ID", "Department", "Job Title", "Employee Status", "Hire Date", "Salary"
            }
        ));
        jScrollPane1.setViewportView(view);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 43, 654, 401));

        btn3.setBackground(new java.awt.Color(0, 0, 204));
        btn3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn3.setForeground(new java.awt.Color(255, 255, 255));
        btn3.setText("Update");
        btn3.setToolTipText("");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        getContentPane().add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, -1, -1));

        btn4.setBackground(new java.awt.Color(255, 45, 25));
        btn4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn4.setForeground(new java.awt.Color(255, 255, 255));
        btn4.setText("Delete");
        btn4.setToolTipText("");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        getContentPane().add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg.jpg"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        Connection con = Database.connection();

        try{

            PreparedStatement ptst = con.prepareStatement("INSERT INTO employment_details (employee_id, department, job_title, employment_status, hire_date, salary) VALUES (?, ?, ?, ?, ?, ?)");

// Assuming txtemployeeid, txtdepartment, txtjobtitle, cmbemploymentstatus, txthiredate, txtsalary are the components for user input
ptst.setInt(1, Integer.parseInt(txtemployeeid.getText())); // Assuming employee ID is an integer
ptst.setString(2, txtdepartment.getText());
ptst.setString(3, txtjobtitle.getText());
ptst.setString(4, txtemploymentstatus.getText()); // Get selected item from JComboBox
ptst.setString(5, txthiredate.getText()); // Assuming hire date is entered as text
double salary = Double.parseDouble(txtsalary.getText());
    ptst.setDouble(6, salary); 

// Execute the query
int i = ptst.executeUpdate();

            if(i != 0){
                JOptionPane.showMessageDialog(null, "Employee Details Added Successfully !");
                showData();
                clear();
            }
        

} catch (SQLException e) {
    e.printStackTrace(); // Handle SQL exception
} catch (NumberFormatException e) {
    System.out.println("Invalid employee ID or salary format."); // Handle number format exception
}
    }//GEN-LAST:event_btn1ActionPerformed

    private void txtsalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsalaryActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        Index id =  new Index();
        id.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        Connection con = Database.connection();
        try {
            PreparedStatement ptst = con.prepareStatement("UPDATE employment_details SET department=?, job_title=?, employment_status=?, hire_date=?, salary=? WHERE employee_id=?");

            // Assuming txtid, txtdepartment, txtjobtitle, txtemploymentstatus, txthiredate, txtsalary are the components for user input
            ptst.setString(1, txtdepartment.getText());
            ptst.setString(2, txtjobtitle.getText());
            ptst.setString(3, txtemploymentstatus.getText()); // Get selected item from JComboBox
            ptst.setString(4, txthiredate.getText()); // Assuming hire date is entered as text
            BigDecimal salary = new BigDecimal(txtsalary.getText());
            ptst.setBigDecimal(5, salary);
            ptst.setInt(6, Integer.parseInt(txtemployeeid.getText())); // Assuming employee ID is an integer

            // Execute the update query
            int i = ptst.executeUpdate();

            if (i != 0) {
                JOptionPane.showMessageDialog(null, "Employee Details Updated Successfully !");
                showData();
                clear();
            }
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "You Must Fill all Fields to Update the Database!!!");
        } catch (NumberFormatException e) {
            System.out.println("Invalid employee ID or salary format.");
        }
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
         Connection con = Database.connection();
    try {
        PreparedStatement ptst = con.prepareStatement("DELETE FROM employment_details WHERE employee_id=?");
        ptst.setInt(1, Integer.parseInt(txtemployeeid.getText()));

        int i = ptst.executeUpdate();

        if (i != 0) {
            JOptionPane.showMessageDialog(null, "Employee Details Deleted Successfully !");
            showData();
            clear(); // Assuming clear() method clears the input fields
        } else {
            JOptionPane.showMessageDialog(null, "No employee found with the provided ID.");
        }
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error deleting employee details from the database.");
    } catch (NumberFormatException e) {
        System.out.println("Invalid employee ID.");
    }

    }//GEN-LAST:event_btn4ActionPerformed

    private void txtemploymentstatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemploymentstatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemploymentstatusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Assign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Assign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Assign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Assign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Assign().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtdepartment;
    private javax.swing.JTextField txtemployeeid;
    private javax.swing.JTextField txtemploymentstatus;
    private javax.swing.JTextField txthiredate;
    private javax.swing.JTextField txtjobtitle;
    private javax.swing.JTextField txtsalary;
    private javax.swing.JTable view;
    // End of variables declaration//GEN-END:variables

    private void clear() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
